# Generated by Django 5.2.1 on 2025-05-11 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_monto_gasto_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grupo'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
    ]
